name: Compile And Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: [macos-latest] # 👀 This action only works on macOS
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      # Do you stuff to build the project
      - uses: AlexHaible/streamdeck-action@0.0.3
        with:
          input-directory: "/src/quest.alex.beledar.sdPlugin" # Where is your code
          output-directory: "/release" # Where you want the .streamDeckPlugin
      # Create an artifact to download it
      - name: Upload .streamDeckPlugin artifact
        uses: softprops/action-gh-release@v2
        with:
          files: ./release/quest.alex.beledar.streamDeckPlugin