on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: [macos-latest] # 👀 This action only works on macOS
    steps:
      - uses: actions/checkout@v2
      # Do you stuff to build the project
      - uses: SantiMA10/streamdeck-action@v0.0.2
        with:
          input-directory: "/src/quest.alex.beledar.sdPlugin" # Where is your code
          output-directory: "/release" # Where you want the .streamDeckPlugin
      # Create an artifact to download it
      - name: Upload .streamDeckPlugin artifact
        uses: actions/upload-artifact@v4
        with:
          name: quest.alex.beledar.streamDeckPlugin
          path: ./release/